# TECHMIMO


Autor: Rafael Pereira da Silva

Seguem alguns recados para ajudá-los e para contribuir com o curso:

- Fiquem à vontade para me contatar pelo Linkdin, costumo responder por lá também: https://www.linkedin.com/in/rafael-pereira-da-silva-23890799/

- Fiquem a vontade para compartilharem o certificado do curso no Linkedin. Eu costumo curtir e comentar para dar mais credibilidade

- Vocês podem usar esses notebooks para resolver os exercícios e desafios

- Não se esqueçam de avaliar o curso e dar feedback, eu costumo criar conteúdos baseado nas demandas de vocês
- Se tiverem gostando do curso, recomendem aos amigos, pois isso também ajuda a impulsionar e a crescer a comunidade
-  Bons estudos e grande abraços!


## Sobre o Material

Este material é parte do curso **Python para Engenheiros e Cientistas** e está sobre a licença MIT.
Caso você tenha interesse em conhecer o curso, acesso o link abaixo.


https://www.udemy.com/course/python-para-engenheiros-e-cientistas/?referralCode=FA25B2C024FF2D3F8232


Algumas aulas, exercícios e desafios estarão sem códigos propositalmente para que o aluno possa preencher.


# Seção 8 - Fundamentos de Numpy


## 8.1 Arrays 
Acesse:
- https://numpy.org/doc/
- https://numpy.org/doc/1.18/numpy-user.pdf
- https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing

#### Sobre
O Numpy é uma biblioteca que permite construirmos *arrays* multidimensionais.

#### Propriedades de arrays


| Propriedade | Retorna  | Descrição |
| :-- | :-- | :-- |
| ndim | int |  número de dimensões (axes) |
| shape |  tupla |  quantidade de dados em cada dimensão |
| size | int | número de elementos |
| dtype| dtype | tipo das variáveis dos elementos |

In [26]:
import numpy as np

a_1 = np.array([1,1,1])
a_1.ndim

1

In [31]:
a_2 = np.array([[3,2.,3],[4,5,6]])
a_2

array([[ 3.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [36]:
a_4 = np.arange(40).reshape(2,2,2,5)
a_4.dtype

dtype('int32')

## 8.2 Operações com arrays

### Algumas funcionalidades do Numpy
| Comando | Tipo | Descrição |
| :-- | :-- | :-- |
| sin,cos,exp,sqrt | Função | seno,cosseno,exponencial,raíz quadrada |
| pi,nan,inf | constantes(float) | pi, similar a None, infinito |
| +,-,*,/ | operadores | operações aritimética |
| ARRAY1.dot(ARRAY2) | método | multiplicação matricial |



In [7]:
import numpy as np

a = np.sin(np.pi/2)
a

1.0

In [6]:
type(np.pi)

float

In [9]:
type(np.inf)

float

In [12]:
type(np.nan)

float

In [11]:
None

In [20]:
a_1 = np.array([[1,2,3]])
a_1

array([[1, 2, 3]])

In [22]:
a_2 = np.array([4,5,6])
a_2

array([4, 5, 6])

In [17]:
a_1 - 5

array([-4, -3, -2])

In [21]:
a_1*a_2

array([[ 4, 10, 18]])

In [24]:
a_1.dot(a_2)

array([32])

In [25]:
import sympy as sp

s_1 = sp.Matrix([[1,2,3]])
s_1

Matrix([[1, 2, 3]])

In [27]:
s_2 = sp.Matrix([4,5,6])
s_2

Matrix([
[4],
[5],
[6]])

In [28]:
s_1*s_2

Matrix([[32]])

## 8.3 Funções de criação de arrays

### Algumas funções numpy para criar arrays

| Função | Descrição |
| :-- | :-- |
| zeros(*shape*) | array preenchido com zeros |
| ones(*shape*) | array preenchido com uns |
| eye(*dimensão*) | matriz identidade |
| arange(*início, fim, passo*) | cria um array unidimensioanl |
| linspace(*início, fim, quantidade*) | cria um array unidimensioanl |
| vstack([*arrays*]) e hstack([*arrays*]) | adiciona elementos de um ou mais arrays |


Métodos para dimensionar os arrays:
 - reshape --> retorna um array com o shape indicado
 - resize --> modifica o shape do array em que está sendo aplicado



In [88]:
import numpy as np

a_4 = np.ones(6)*11
a_4

array([ 11.,  11.,  11.,  11.,  11.,  11.])

In [91]:
a_5 = np.eye(4)
a_5.ndim

2

In [96]:
a_6 = np.arange(0,10,0.5)
a_6

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5])

In [98]:
a_7 = np.linspace(0,10,12)
a_7.size

12

In [106]:
a_8 = np.ones(8)
a_8.reshape(2,4)
a_8

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [107]:
a_9 = np.ones(8)
a_9.resize(2,4)
a_9

a_10 = np.zeros(8)
a_10.resize(2,4)
a_10

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [108]:
a_11 = np.vstack((a_9,a_10))
a_11

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [116]:
a_12 = np.hstack((a_9,a_10))
a_13 = np.vstack((a_11,a_9))
a_13

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

## 8.4 Método copy




| Método | Descrição |
| :-- | :-- |
| .copy() | faz a cópia (deep copy) do array. Cuidado! O sinal de igual não executa essa função |


Nota - a propriedade **base** retorna o array utilizado para criar o array em questão



In [1]:
# A ser preenchido pelo aluno (aula gratuita liberada)

## 8.5 Métodos matemáticos para arrays

### Alguns métodos matemáticos para arrays



| Método | Descrição |
| :-- | :-- |
| .max() / .min()  | retona os valores máximo e mínimo|
| .argmax() / .argmin() | retorna os índices de valor máximo e mínimo |
| .sum() / .mean() / .std() | soma, média e desvio padrão |
|  .cumsum() | retorna um array com a soma acumulada |



In [29]:
import numpy as np

my_array = np.arange(8).reshape(2,4)**2
my_array[0][0] =11
my_array

array([[11,  1,  4,  9],
       [16, 25, 36, 49]], dtype=int32)

In [33]:
my_array.min(axis=1)


array([ 1, 16], dtype=int32)

In [35]:
my_array.argmin()

1

In [40]:
my_array.sum()

151

In [39]:
my_array.cumsum()

array([ 11,  12,  16,  25,  41,  66, 102, 151], dtype=int32)

## 8.6 Índices e fatias de arrays (Indexing and slicing)

### Guidelines

https://scipy-lectures.org/intro/numpy/array_object.html#indexing-and-slicing


| Sintaxe | Descrição |
| :-- | :-- |
| [i] | para 1 dimensão funciona como nas listas |
| [:i] | exibe um array que vai do índice 0 até o anterior ao i|
| [i:] | exibe um array que vai do índice posterior ao i até o último índice|
|
[::i] | exibe todos os elementos variando de i em i |
| [::-i] | exibe a sequência de elementos de trás pra frente variando de i em i |
| [a:b:c] | início, fim, step |
| [i,j] | para exibir um elemento de uma matriz |
| [i,a:b] | retorna uma fatia da linha i com elementos das colunas de a até b |
| [n,i,j] | outra dimensão, linha, coluna |


Quando criamos um subarray o numpy pode compartilhar memória entre arrays (como mostrado em aulas anteriores com a propriedade .base). Para descobrir se um array compartilha memória com outro use: **np.may_share_memory(a, c)**




In [2]:
# A ser preenchido pelo aluno

## 8.7 Operações com vetores e matrizes no Numpy


- https://numpy.org/doc/stable/reference/routines.linalg.html
- https://numpy.org/doc/stable/reference/generated/numpy.cross.html


| Método | Descrição |
| :-- | :-- |
|.dot(a,b) ou @ | retorna o produto escalar entre os vetores **a** e **b** |
| .cross(a,b) | retorna o produto vetorial entre os vetores **a** e **b** |
| .inner(a,b) e .outer(a,b) | retorna o produto interno e externo entre os vetores **a** e **b** |
| .linalg.norm(a) | retorna a norma do vetor **a** |
| .matmul(a,b) | produto entre as matrizes **a** e **b** |
| .linalg.det(A) | retorna o determinante da matriz **A** |
| .linalg.inv(A) | retorna a matriz inversa de **A** |

### Vetores

In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3])


a@a
np.dot(a,a)

14

In [30]:
np.inner(a,a)

14

In [31]:
np.outer(a,a)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [50]:
np.linalg.norm(a)
#np.sqrt(1**2+2**2+3**2)

3.7416573867739413

In [35]:
# produto vetorial

In [37]:
v1 = np.array([1,0,0])
v2 = np.array([0,1,0])

np.cross(v1,v2)

array([0, 0, 1])

In [33]:
import sympy as sp

a_s = sp.Matrix([1,2,3])


a_s.T*a_s

Matrix([[14]])

In [34]:
a_s*a_s.T

Matrix([
[1, 2, 3],
[2, 4, 6],
[3, 6, 9]])

### Matrizes

In [54]:
#multiplicação numpy

A = np.array([[1,2],[4,4]])

np.matmul(A,A)

A@A # (cuidado com o A*A)

array([[ 9, 10],
       [20, 24]])

In [55]:
A_s = sp.Matrix([[1,2],[4,4]])

A_s*A_s


Matrix([
[ 9, 10],
[20, 24]])

In [56]:
np.linalg.det(A)

-4.0

In [57]:
np.linalg.inv(A)

array([[-1.  ,  0.5 ],
       [ 1.  , -0.25]])

In [58]:
np.linalg.inv(A)@A

array([[1., 0.],
       [0., 1.]])

## 8.8 Autovalor e autovetor


- https://numpy.org/doc/stable/reference/routines.linalg.html


| Método | Descrição |
| :-- | :-- |
| linalg.eig(A) | retorna os autovalores e autovetores da matrix **A** |

### Sympy

In [80]:
import sympy as sp

lamb = sp.symbols('lambda')
A_s = sp.Matrix([[5.,3,-1],
                 [3,4,0],
                 [-1,0,2]])

eq_carac = sp.simplify(((A - lamb*sp.eye(3))))
eq_carac.det()

10*lambda + (2 - lambda)*(4 - lambda)*(5 - lambda) - 22

In [79]:
sp.solve(eq_carac.det())

[1, 5 - sqrt(7), sqrt(7) + 5]

### Numpy

In [59]:
import numpy as np

A = np.array([[5,3,-1],
              [3,4,0],
              [-1,0,2]])


In [64]:
l,v = np.linalg.eig(A)
l

array([7.64575131, 1.        , 2.35424869])

## 8.9 Sistemas lineares

- https://numpy.org/doc/stable/reference/routines.linalg.html


| Método | Descrição |
| :-- | :-- |
| .linalg.solve(A, B) | resolve um sistema do tipo AX= B |

In [3]:
# A ser preenchido pelo aluno